// <auto-generated />
namespace BITCollege_TP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedStoredProcedures : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedStoredProcedures));
        
        string IMigrationMetadata.Id
        {
            get { return "202402250205473_addedStoredProcedures"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
